// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Entities;

public partial class Patient
{
    public int PatientId { get; set; }

    public string Name { get; set; }

    public int Age { get; set; }

    public string State { get; set; }

    public string City { get; set; }

    public string Address { get; set; }

    public string Pin { get; set; }

    public string Mobile { get; set; }

    public int Gender { get; set; }

    public virtual ICollection<Appointment> Appointments { get; set; } = new List<Appointment>();
}